-- El orden importa por las claves foráneas
DROP TABLE IF EXISTS alquiler;
DROP TABLE IF EXISTS pelicula_actor;
DROP TABLE IF EXISTS pelicula;
DROP TABLE IF EXISTS actor;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS director;

-- Tabla DIRECTOR
CREATE TABLE director
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- Tabla PELICULA
CREATE TABLE pelicula
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR(200) NOT NULL,
    genero       VARCHAR(50),
    anio_estreno INT,
    puntuacion   DECIMAL(3, 1),
    director_id  BIGINT,
    CONSTRAINT fk_pelicula_director
        FOREIGN KEY (director_id)
            REFERENCES director (id)
            ON DELETE SET NULL
);

-- Tabla ACTOR
CREATE TABLE actor
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

-- Tabla intermedia MANY-TO-MANY: PELICULA_ACTOR
CREATE TABLE pelicula_actor
(
    pelicula_id BIGINT NOT NULL,
    actor_id    BIGINT NOT NULL,
    PRIMARY KEY (pelicula_id, actor_id),
    CONSTRAINT fk_pelicula_actor_pelicula
        FOREIGN KEY (pelicula_id)
            REFERENCES pelicula (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_pelicula_actor_actor
        FOREIGN KEY (actor_id)
            REFERENCES actor (id)
            ON DELETE CASCADE
);

-- Tabla CLIENTE
CREATE TABLE cliente
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email  VARCHAR(150) NOT NULL UNIQUE
);

-- Tabla ALQUILER
CREATE TABLE alquiler
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id       BIGINT NOT NULL,
    pelicula_id      BIGINT NOT NULL,
    fecha_alquiler   DATE   NOT NULL,
    fecha_devolucion DATE,
    CONSTRAINT fk_alquiler_cliente
        FOREIGN KEY (cliente_id)
            REFERENCES cliente (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_alquiler_pelicula
        FOREIGN KEY (pelicula_id)
            REFERENCES pelicula (id)
            ON DELETE CASCADE
);